### ISSUE TITLE
Exporter doesn't support port in the Host HTTP header

### ISSUE THREAD

**Issue by stefanluptak** [cpanato/github_actions_exporter#3]
When I configure my target to scrape as this:
```yaml
- job_name: 'some_job'
    scheme: https
    static_configs:
    - targets: ['example.com']
```
Prometheus will try to scrape the endpoint with a request containing HTTP header `Host: example.com:443`. Apparently, Go `net` library is not able to deal with this and returns **404**. I am not very familiar with Go, but it looks like it has been discussed here https://github.com/golang/go/issues/10463
I put my exporter behind a Nginx proxy for now and it's working, but I would like to use it directly in the future.
